Parameters:
  env: 
    Type: String
    Description: Environment name for site.
  # DomainName:
  #   Type: String
  #   Description: Domain name for site.
  # HostedZoneId:
  #   Type: String
  #   Description: Hosted zone id for site.
  
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "crc-bucket-${env}"
      Tags:
      - Key: Name
        Value: crc-bucket
      - Key: Environment
        Value: !Ref env

    

Outputs:
  BucketName:
    Description: Name of the bucket
    Value: !Ref MyBucket
    Export:
      Name: !Sub "crc-bucket-${env}"
  BucketArn:
    Description: Arn of the bucket
    Value: !GetAtt MyBucket.Arn
    Export:
      Name: !Sub "crc-bucket-arn-${env}"