Parameters:
  env: 
    Type: String
    Description: Environment name for site.
  DomainName:
    Type: String
    Description: Domain name for site.
  HostedZoneId:
    Type: String
    Description: Hosted zone id for site.

Resources:
  
  ### S3 RESOURCES ###
  # s3 bucket for site
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "crc-bucket-${env}"
      OwnershipControls:
           Rules:
                - ObjectOwnership: BucketOwnerPreferred
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
      - Key: Name
        Value: crc-bucket
      - Key: Environment
        Value: !Ref env

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: 
              -  !Sub "${MyBucket.Arn}/*"
              -  !GetAtt MyBucket.Arn
            Principal: "*"

  # CloudFront distribution for redirecting to s3 bucket
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront distribution for redirecting to S3 bucket
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: MyBucketOrigin
            DomainName: !GetAtt MyBucket.WebsiteURL
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: MyBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Tags:
          - Key: Name
            Value: crc-cloudfront
          - Key: Environment
            Value: !Ref env



  # Route53 record for site
  Route53Record:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ## Deployment mechanism for site
  # CodeBuild project for site
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "crc-build-${env}"
      Description: !Sub "Build project for ${env}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: S3
        Location: !Ref CodeBuildArtifactBucket
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref MyBucket
          - Name: ENV
            Value: !Ref env
      Source:
        Type: GITHUB
        Location: https://github.com/rpuffe/CRC.git
        BuildSpec: buildspec.yml
      SourceVersion: main
      Tags:
        - Key: Name
          Value: crc-build
        - Key: Environment
          Value: !Ref env
  # CodeBuild role for site
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "crc-build-role-${env}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub "crc-build-policy-${env}"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:*
                Resource: 
                  - !Sub "arn:aws:s3:::${MyBucket}/*"
                  - !Sub "arn:aws:s3:::${MyBucket}"
                  - !Sub "arn:aws:s3:::${CodeBuildArtifactBucket}/*"
                  - !Sub "arn:aws:s3:::${CodeBuildArtifactBucket}"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: 
                  - !Sub "arn:aws:s3:::${MyBucket}"
                  - !Sub "arn:aws:s3:::${CodeBuildArtifactBucket}"
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/*"
              - Effect: Allow
                Action:
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:UpdateDistribution
                Resource: "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess 
  
  # Codebuild Artifact s3 bucket for site
  CodeBuildArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "crc-build-artifact-${env}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
      - Key: Name
        Value: crc-build-artifact
      - Key: Environment
        Value: !Ref env

Outputs:
  BucketName:
    Description: Name of the bucket
    Value: !Ref MyBucket
    Export:
      Name: !Sub "crc-bucket-${env}"
  BucketArn:
    Description: Arn of the bucket
    Value: !GetAtt MyBucket.Arn
    Export:
      Name: !Sub "crc-bucket-arn-${env}"